### ISSUE TITLE
AI生成的思维导图图

### ISSUE THREAD

**Issue by Guohuan-Feng** [ZJU-LLMs/Foundations-of-LLMs#10]
这个网站上的每篇文章综述，前面都有一个AI生成的图，请问这个AI生成的图是什么软件生成的呀，可以方便告诉我下吗？

**Comment by wenyisir** [comment]
你好，我们使用的是gpt-4o生成的

**Comment by LJHzju** [comment]
你好，如果指的是论文分享最前面的思维导图，那个是使用xmind手动完成的。
