### ISSUE TITLE
为什么无法下载？

### ISSUE THREAD

**Issue by jackyrong** [ZJU-LLMs/Foundations-of-LLMs#8]
Error rendering embedded code

Invalid PDF

**Comment by wenyisir** [comment]
You can download the ZIP file directly from the repository's homepage.

**Comment by bigbigwatermalon** [comment]
![image](https://github.com/user-attachments/assets/cee62af6-4485-4a1c-9886-8b0e69fe2772)
Hello! On this PDF web page, clicking on the download icon will automatically start the download using the browser.
